type = "cosmos"
name = "centauri"
rpc_url = "http://127.0.0.1:26657/"
grpc_url = "http://127.0.0.1:9090/"
websocket_url = "ws://127.0.0.1:26657/websocket"
chain_id = "centauri-dev"
client_id = "07-tendermint-1"
connection_id = "connection-0"
account_prefix = "pica"
fee_denom = "ppica"
fee_amount = "9223372036854776"
gas_limit = 9223372036854775806
store_prefix = "ibc"
max_tx_size = 20000000
wasm_checksum = "2499377e7b99e1b621f980ffc2f6a9322742717c7ede1bf7c97235440450fffe"
channel_whitelist = [["channel-0", "transfer"], ["channel-0", "transfer"], ["channel-0", "transfer"], ["channel-0", "transfer"]]
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
skip_optional_client_updates = false
max_packets_to_process = 50
skip_tokens_list = []
