on:
  push:
    paths:
      - '**.go'      
      - 'go.sum'
  pull_request:
    branches:
      - release/v6.3.x
name: compatibility check
# This CI job will do what many validators do: get a recent polkachu snapshot and run.  
# For now, this ci job may need to be manually updated to keep the snapshot up to date. 
# In a success case, this job will run the chain for ten minutes, computing each block and arriving at the same block hash / app hash. 
# This way, we can test various scenarios and know that changes are highly unlikely to be breaking. 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: |
          go install ./...
          centaurid init github
          wget -q https://snapshots.polkachu.com/snapshots/composable/composable_3035461.tar.lz4
          wget https://raw.githubusercontent.com/notional-labs/composable-networks/main/mainnet/genesis.json
          mv genesis.json  ~/.banksy/config/genesis.json
          mv composable_3035461.tar.lz4 ~/.banksy/composable_3035461.tar.lz4
          cd ~/.banksy
          lz4 -d composable_3035461.tar.lz4 | tar -xvf -
          timeout 10m centaurid start --p2p.seeds "ebc272824924ea1a27ea3183dd0b9ba713494f83@composable-mainnet-seed.autostake.com:26976,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:22256,d2362ebcdd562500ac8c4cfa2214a89ad811033c@seeds.whispernode.com:22256" || ( [[ $? -eq 124 ]] && echo "HAPPY: Timeout reached without apphash issues" )
        
